config/routes.rb
Rails.application.routes.draw do
  resources :joboffers
  resources :searches
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joboffer.rb
class Joboffer < ApplicationRecord
  has_one_attached:image

  def self.search(search)
    if search
      where(["job_title LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/models/search.rb
class Search < ApplicationRecord

    def search_job
      jobs = Joboffer.all

      jobs= jobs.where(['job_title LIKE ?',"%#{keywords}%"]) if keywords.present?
      jobs= jobs.where(["minimum_japaneseskill LIKE ?",minimum_japanese]) if minimum_japanese.present?
      jobs= jobs.where(["salary >= ?", min_salary]) if min_salary.present?
      jobs= jobs.where(["salary <= ?",max_salary]) if max_salary.present?

      return jobs

    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/joboffers_controller.rb
class JoboffersController < ApplicationController
  before_action :set_joboffer, only: [:show, :edit, :update, :destroy]

  # GET /joboffers
  # GET /joboffers.json
  def index
    @joboffers = Joboffer.search(params[:search])
  end

  # GET /joboffers/1
  # GET /joboffers/1.json
  def show
  end

  # GET /joboffers/new
  def new
    @joboffer = Joboffer.new
  end

  # GET /joboffers/1/edit
  def edit
  end

  # POST /joboffers
  # POST /joboffers.json
  def create
    @joboffer = Joboffer.new(joboffer_params)

    respond_to do |format|
      if @joboffer.save
        format.html { redirect_to @joboffer, notice: 'Joboffer was successfully created.' }
        format.json { render :show, status: :created, location: @joboffer }
      else
        format.html { render :new }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joboffers/1
  # PATCH/PUT /joboffers/1.json
  def update
    respond_to do |format|
      if @joboffer.update(joboffer_params)
        format.html { redirect_to @joboffer, notice: 'Joboffer was successfully updated.' }
        format.json { render :show, status: :ok, location: @joboffer }
      else
        format.html { render :edit }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joboffers/1
  # DELETE /joboffers/1.json
  def destroy
    @joboffer.destroy
    respond_to do |format|
      format.html { redirect_to joboffers_url, notice: 'Joboffer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joboffer
      @joboffer = Joboffer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def joboffer_params
      params.require(:joboffer).permit(:job_title, :salary, :minimum_japaneseskill, :job_description, :shift, :place, :image)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def new
      @search = Search.new
      @categories = Joboffer.distinct.pluck(:minimum_japaneseskill)
    end

    def create
      @search = Search.create(search_params)
      redirect_to @search

    end

    def show
      @search = Search.find(params[:id])

    end

    private

    def search_params
      params.require(:search).permit(:keywords,:minimum_japanese,:min_salary,:max_salary)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/joboffers_helper.rb
module JoboffersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%=link_to"home", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%=link_to"job offers", joboffers_path, class:'nav-link active' %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome to our job search website!!</h1>

app/views/joboffers/_form.html.erb
<%= form_with(model: joboffer, local: true) do |form| %>
  <% if joboffer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joboffer.errors.count, "error") %> prohibited this joboffer from being saved:</h2>

      <ul>
        <% joboffer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :job_title %>
    <%= form.text_field :job_title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary %>
  </div>

  <div class="field">
    <%= form.label :minimum_japaneseskill %>
    <%= form.text_field :minimum_japaneseskill %>
  </div>

  <div class="field">
    <%= form.label :job_description %>
    <%= form.text_field :job_description %>
  </div>

  <div class="field">
    <%= form.label :shift %>
    <%= form.text_field :shift %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/joboffers/edit.html.erb
<h1>Editing Joboffer</h1>

<%= render 'form', joboffer: @joboffer %>

<%= link_to 'Show', @joboffer %> |
<%= link_to 'Back', joboffers_path %>

app/views/joboffers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Joboffers List</h1>

<%#
<table class='table table-striped'>
  <thead class='thead-dark'>
    <tr>
      <th>Job title</th>
      <th>Salary</th>
      <th>Minimum japaneseskill</th>
      <th>Job description</th>
      <th>Shift</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>
%>
  <tbody>
    <%# @joboffers.each do |joboffer| %>
      <tr>
        <td><%#= joboffer.job_title %></td>
        <td><%#= joboffer.salary %></td>
        <td><%#= joboffer.minimum_japaneseskill %></td>
        <td><%#= joboffer.job_description %></td>
        <td><%#= joboffer.shift %></td>
        <td><%#= joboffer.place %></td>
        <td><%#= link_to 'Detail', joboffer %></td>
        <td><%#= link_to 'Edit', edit_joboffer_path(joboffer) %></td>
        <td><%#= link_to 'Destroy', joboffer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

  <%= form_tag joboffers_path, :method=>'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'search' %>
  <% end %>
<br/>
<%= link_to 'Advanced Search',new_search_path,class:"btn btn-secondary" %>
<br/>
<br>
<% @joboffers.each do |joboffer| %>
<div class="card" style="width: 20rem; height:auto">
  <%= image_tag joboffer.image,style:'width:100%' %>
  <div class="card-body">
    <h5 class="card-title"><%= joboffer.job_title %></h5>
    <p class="card-text"><%= joboffer.job_description %></p>
    <%= link_to 'Detail', joboffer,class:'btn btn-primary' %>
    <%= link_to 'Destroy', joboffer, method: :delete,class:'btn btn-danger', data: { confirm: 'Are you sure?' } %>

  </div>
</div>


<% end %>



<br>

<%= link_to 'New Joboffer', new_joboffer_path, class:"btn btn-secondary" %>

app/views/joboffers/new.html.erb
<h1>New Joboffer</h1>

<%= render 'form', joboffer: @joboffer %>

<%= link_to 'Back', joboffers_path %>

app/views/joboffers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">
    <%= @joboffer.job_title %>
  </h1>


    <%= image_tag @joboffer.image.variant(resize:'400x400').processed  %>



  <p class="lead">
    <strong>Salary:</strong>
    <%= @joboffer.salary %>
  </p>

  <p class="lead">
    <strong>Minimum japaneseskill:</strong>
    <%= @joboffer.minimum_japaneseskill %>
  </p>

  <p class="lead">
    <strong>Job description:</strong>
    <%= @joboffer.job_description %>
  </p>

  <p class="lead">
    <strong>Shift:</strong>
    <%= @joboffer.shift %>
  </p>

  <p class="lead">
    <strong>Place:</strong>
    <%= @joboffer.place %>
  </p>
</div>



<%= link_to 'Edit', edit_joboffer_path(@joboffer),class:"btn btn-secondary" %> |
<%= link_to 'Back', joboffers_path,class:'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Job search website</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    <%= render 'home/header'  %>
    <div class='container'>
      <br/>
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_for @search, html: {class: "pure-form"} do |s| %>

  <div class="field">
    <%= s.label :keywords %><br/>
    <%= s.text_field :keywords %>
  </div>

  <div class="field">
    <%= s.label :minimum_japanese %><br/>
    <%= s.select :minimum_japanese, options_for_select(@categories), :include_blank => true %>
  </div>

  <div class="field">
    <%= s.label :min_salary, "Min Salary" %> - <%= s.text_field :min_salary,size:10  %>
    <%= s.label :max_salary, "Max Salary" %> - <%= s.text_field :max_salary,size:10  %>
  </div>

  <div class="actions"><%= s.submit "Search",class:'btn btn-secondary' %></div>

<% end %>
<br/>
<%= link_to 'Back',joboffers_path,class:'btn btn-secondary' %>

app/views/searches/show.html.erb
<h1>Search Result</h1>

<% if @search.search_job.empty?  %>

  <p>No Records Found</p>

<% else %>

  <%= @search.search_job.each do |c| %>
  <br>

  <div class="div">
    <h1><%= c.job_title %></h1>
    <p>Minimum Japanese: <%= c.minimum_japaneseskill %></p>
    <p>Salary: <%= c.salary %></p>
    <%= link_to 'Detail', joboffer_path,class:'btn btn-primary' %>


  </div>
  <% end %>

<%  end %>